name: Test example scripts

on:
  push:
    branches: [ "main", "gh_action" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: test-examples
    strategy:
      fail-fast: false

    env:
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      # - uses: r-lib/actions/setup-renv@v2
      
      # - uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     extra-packages: devtools
        
      - name: Install packages and render Rmarkdown files
        run: |
          echo "Rendering the page..."
          Rscript -e 'install.packages(c("knitr", "rmarkdown"))'
          Rscript -e 'rmarkdown::render(input = "examples/DownloadandSaveModelLocally.Rmd")'

      - name: Upload check results
        if: failure()  # if any of the previous steps fail, export a log
        uses: actions/upload-artifact@main
        with:
          name: results
          path: check
